In [1]:
import torch
torch.__version__

'1.13.1+cu117'

In [2]:
# 初始化
x = torch.empty(5, 3)
x

tensor([[ 7.4929e+28,  4.5773e-41,  7.4929e+28],
        [ 4.5773e-41, -4.2091e+28,  3.0942e-41],
        [ 1.7302e+29,  4.5773e-41, -1.2956e+31],
        [ 3.0942e-41,  0.0000e+00,  7.0065e-45],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45]])

In [4]:
# 随机数初始化
x = torch.rand(5, 3)
x

tensor([[0.7445, 0.9466, 0.1210],
        [0.7789, 0.6010, 0.0854],
        [0.8653, 0.3112, 0.2254],
        [0.4408, 0.9573, 0.7544],
        [0.9658, 0.0223, 0.6833]])

In [5]:
# 全0初始化
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
# 从List创建张量
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [12]:
# 全1初始化
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
# 随机指定类型初始化
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-1.1971, -2.3589,  0.2148],
        [ 0.1279,  0.5023, -0.5882],
        [ 0.1528,  0.6347,  0.0475],
        [-0.7317, -0.2430,  0.0592],
        [-0.4062,  1.5036,  0.4807]])

In [14]:
# 输出大小
x.size()

torch.Size([5, 3])

In [15]:
# 张量加法
y = torch.rand(5, 3)
x + y

tensor([[-0.2735, -2.2036,  0.3911],
        [ 0.9798,  1.4971, -0.4780],
        [ 0.3324,  1.3519,  0.4084],
        [-0.5714, -0.1136,  1.0500],
        [-0.2855,  1.6451,  0.7077]])

In [16]:
# torch自带的张量加法
torch.add(x, y)

tensor([[-0.2735, -2.2036,  0.3911],
        [ 0.9798,  1.4971, -0.4780],
        [ 0.3324,  1.3519,  0.4084],
        [-0.5714, -0.1136,  1.0500],
        [-0.2855,  1.6451,  0.7077]])

In [17]:
# 索引
x[:, 1]

tensor([-2.3589,  0.5023,  0.6347, -0.2430,  1.5036])

In [35]:
# view操作可以改变矩阵维度
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [40]:
# 与numpy协同
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [41]:
# numpy转tensor
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)