In [17]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction import DictVectorizer

from sklearn.decomposition import PCA

定义使用数据集

In [25]:
iris = load_iris()
data = [[2, 8, 4, 5], [6, 3, 0, 8], [5, 4, 9, 1]]
geoData = [{'city' : '北京', 'temperature' : 100}, {'city' : '上海', 'temperature' : 60}, {'city' : '深圳', 'temperature' : 30}]

标准化

In [22]:
transfer = StandardScaler()
data_new = transfer.fit_transform(data)
print(data_new)

[[-1.37281295  1.38873015 -0.09053575  0.11624764]
 [ 0.98058068 -0.9258201  -1.1769647   1.16247639]
 [ 0.39223227 -0.46291005  1.26750044 -1.27872403]]


字典特征抽取

In [27]:
transfer = DictVectorizer(sparse=False)
data_new = transfer.fit_transform(geoData)
print(data_new)

[[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]


主成分分析PCA降维

In [21]:
transfer = PCA(n_components=2)
data_new = transfer.fit_transform(data)
print(data_new)

[[-3.13587302e-16  3.82970843e+00]
 [-5.74456265e+00 -1.91485422e+00]
 [ 5.74456265e+00 -1.91485422e+00]]
